package com.laamware.ejercito.doc.web.util;

/**
 * Enumeración de roles del sistema.
 *
 * @author jgarcia@controltechcg.com
 * @since 1.8
 * @version 05/11/2018 Issue #162 (SICDI-Controltech) feature-162
 */
public enum RolConstants {
    ADMIN_ARCHIVO_CENTRAL,
    ADMIN_BANDEJAS,
    ADMIN_CAPACITACION,
    ADMIN_CARGOS,
    ADMIN_CLASIFICACIONES,
    ADMIN_DEPENDENCIAS,
    ADMIN_DESTINATARIOS,
    ADMIN_DOMINIO,
    ADMIN_FORMATOS,
    ADMIN_GRADOS,
    ADMIN_INFORMES,
    ADMIN_LOG,
    ADMIN_PERFILES,
    ADMIN_PLANTILLAS,
    ADMIN_PLANTILLA_TRANSF_ARCHIVO,
    ADMIN_PROCESOS,
    ADMIN_TIPO_DOCUMENTO,
    ADMIN_TIPOLOGIA,
    ADMIN_TIPOS_DESTINATARIO,
    ADMIN_TRD,
    ADMIN_USUARIOS,
    ARCHIVO_CENTRAL,
    BANDEJAS,
    BUSCAR_X_DOC_FIRMA_ENVIO_UUID,
    PROCESAR_REGISTRO_ACTAS,
    REGISTRO
}
