--
-- Author:  edison.gonzalez@controltechcg.com
-- Created: 21/08/2018 Issue #4 (SICDI-Controltech) feature-4
--

-- -----------------------------------------------------------------------------
-- TRANSFERENCIA_ARCHIVO
-- -----------------------------------------------------------------------------

ALTER TABLE TRANSFERENCIA_ARCHIVO ADD JUSTIFICACION 	VARCHAR2(4000);
ALTER TABLE TRANSFERENCIA_ARCHIVO ADD USUARIO_ASIGNADO 	NUMBER(1);
ALTER TABLE TRANSFERENCIA_ARCHIVO ADD IND_APROBADO 	NUMBER(1);
ALTER TABLE TRANSFERENCIA_ARCHIVO ADD DOC_ID 		VARCHAR2(32);

COMMENT ON COLUMN TRANSFERENCIA_ARCHIVO.JUSTIFICACION       IS 'Justificación de la transferencia.';
COMMENT ON COLUMN TRANSFERENCIA_ARCHIVO.USUARIO_ASIGNADO    IS 'Indica el usuario en el que se encuentra la transferencia-0: Usuario receptor; 1: Usuario emisor; 2: Usuario autorizador';
COMMENT ON COLUMN TRANSFERENCIA_ARCHIVO.IND_APROBADO        IS 'Verifica si la transferencia se encuentra aprobada o no: 0: No aprobada; 1: Aprobada';
COMMENT ON COLUMN TRANSFERENCIA_ARCHIVO.DOC_ID              IS 'Identificador del documento del acta asociada a la transferencia.';

ALTER TABLE TRANSFERENCIA_ARCHIVO ADD CONSTRAINT TAR_DOC_ID_ACTA_FK FOREIGN KEY (DOC_ID) REFERENCES DOCUMENTO (DOC_ID);

-- -----------------------------------------------------------------------------
-- TRANS_JUSTIFICACION_DEFECTO
-- -----------------------------------------------------------------------------

CREATE SEQUENCE seq_TRANS_JUSTIFICACION_DEFECTO;
CREATE TABLE TRANS_JUSTIFICACION_DEFECTO (
  TJD_ID            number(10) NOT NULL, 
  TEXTO_OBSERVACION varchar2(1000) NOT NULL, 
  ACTIVO            number(1) NOT NULL, 
  QUIEN             number(38) NOT NULL, 
  CUANDO            date NOT NULL, 
  QUIEN_MOD         number(38) NOT NULL, 
  CUANDO_MOD        date, 
  PRIMARY KEY (TJD_ID));
  
ALTER TABLE TRANS_JUSTIFICACION_DEFECTO ADD CONSTRAINT FK_TJD_USUARIO_CREADOR FOREIGN KEY (QUIEN) REFERENCES USUARIO (USU_ID);
ALTER TABLE TRANS_JUSTIFICACION_DEFECTO ADD CONSTRAINT FK_TJD_USUARIO_MODIFICA FOREIGN KEY (QUIEN_MOD) REFERENCES USUARIO (USU_ID);

COMMENT ON COLUMN TRANS_JUSTIFICACION_DEFECTO.TJD_ID 			IS 'Identificador de la tabla.';
COMMENT ON COLUMN TRANS_JUSTIFICACION_DEFECTO.TEXTO_OBSERVACION		IS 'Texto de la observación.';
COMMENT ON COLUMN TRANS_JUSTIFICACION_DEFECTO.ACTIVO 			IS 'Indicador de actividad (0=activo;1=inactivo).';
COMMENT ON COLUMN TRANS_JUSTIFICACION_DEFECTO.QUIEN			IS 'ID del usuario creador de la observación.';
COMMENT ON COLUMN TRANS_JUSTIFICACION_DEFECTO.CUANDO			IS 'Fecha y hora de creación de la observación.';
COMMENT ON COLUMN TRANS_JUSTIFICACION_DEFECTO.QUIEN_MOD			IS 'ID del último usuario que modificó la observación.';
COMMENT ON COLUMN TRANS_JUSTIFICACION_DEFECTO.CUANDO_MOD		IS 'Fecha y hora de la última modificación de la observación.';

-- -----------------------------------------------------------------------------
-- TRANSFERENCIA_ESTADO
-- -----------------------------------------------------------------------------

CREATE TABLE TRANSFERENCIA_ESTADO (
  TRA_EST_ID     number(10) NOT NULL, 
  TRA_EST_NOMBRE varchar2(255) NOT NULL, 
  PRIMARY KEY (TRA_EST_ID), 
  CONSTRAINT TRA_ESTADO_UNI_1 
    UNIQUE (TRA_EST_NOMBRE));
	
COMMENT ON COLUMN TRANSFERENCIA_ESTADO.TRA_EST_ID 		IS 'Identificador de la tabla.';
COMMENT ON COLUMN TRANSFERENCIA_ESTADO.TRA_EST_NOMBRE		IS 'Descripcion del estado de la transferencia.';

INSERT INTO TRANSFERENCIA_ESTADO(TRA_EST_ID, TRA_EST_NOMBRE) VALUES (10, 'En construcción');
INSERT INTO TRANSFERENCIA_ESTADO(TRA_EST_ID, TRA_EST_NOMBRE) VALUES (20, 'Pendiente de aceptación');
INSERT INTO TRANSFERENCIA_ESTADO(TRA_EST_ID, TRA_EST_NOMBRE) VALUES (30, 'Pendiente de autorizacion');
INSERT INTO TRANSFERENCIA_ESTADO(TRA_EST_ID, TRA_EST_NOMBRE) VALUES (40, 'Aprobado');
INSERT INTO TRANSFERENCIA_ESTADO(TRA_EST_ID, TRA_EST_NOMBRE) VALUES (50, 'Rechazado');
INSERT INTO TRANSFERENCIA_ESTADO(TRA_EST_ID, TRA_EST_NOMBRE) VALUES (60, 'Transferido');
INSERT INTO TRANSFERENCIA_ESTADO(TRA_EST_ID, TRA_EST_NOMBRE) VALUES (70, 'Anulado');

-- -----------------------------------------------------------------------------
-- TRANSFERENCIA_TRANSICION
-- -----------------------------------------------------------------------------

CREATE SEQUENCE seq_TRANSFERENCIA_TRANSICION;
CREATE TABLE TRANSFERENCIA_TRANSICION (
  TTRA_ID      number(10) NOT NULL, 
  USU_CREACION number(38) NOT NULL, 
  TRA_EST_ID   number(10) NOT NULL, 
  TAR_ID       number(38) NOT NULL, 
  FEC_CREACION date, 
  PRIMARY KEY (TTRA_ID));

COMMENT ON COLUMN TRANSFERENCIA_TRANSICION.TTRA_ID 		IS 'Identificador de la tabla.';
COMMENT ON COLUMN TRANSFERENCIA_TRANSICION.USU_CREACION		IS 'Identificador del usuario quien crea la transición.';
COMMENT ON COLUMN TRANSFERENCIA_TRANSICION.TRA_EST_ID		IS 'Identificador del estado de la transición.';
COMMENT ON COLUMN TRANSFERENCIA_TRANSICION.TAR_ID		IS 'Identificador de la transferencia de archivo.';
COMMENT ON COLUMN TRANSFERENCIA_TRANSICION.FEC_CREACION		IS 'Fecha de creación del registro.';

ALTER TABLE TRANSFERENCIA_TRANSICION ADD CONSTRAINT FK_TRANS_TRANSFERENCIA FOREIGN KEY (TAR_ID) REFERENCES TRANSFERENCIA_ARCHIVO (TAR_ID);
ALTER TABLE TRANSFERENCIA_TRANSICION ADD CONSTRAINT FK_TRANSICION_ESTADO FOREIGN KEY (TRA_EST_ID) REFERENCES TRANSFERENCIA_ESTADO (TRA_EST_ID);
ALTER TABLE TRANSFERENCIA_TRANSICION ADD CONSTRAINT FK_TRANSICION_USUARIO FOREIGN KEY (USU_CREACION) REFERENCES USUARIO (USU_ID);

-- -----------------------------------------------------------------------------
-- TRANSFERENCIA_OBSERVACION
-- -----------------------------------------------------------------------------

CREATE SEQUENCE seq_TRANSFERENCIA_OBSERVACION;
CREATE TABLE TRANSFERENCIA_OBSERVACION (
  TRA_OBS_ID      number(10) NOT NULL, 
  FEC_CREACION    date, 
  USU_ID          number(38) NOT NULL, 
  TAR_ID          number(38) NOT NULL, 
  TRA_OBSERVACION varchar2(500), 
  PRIMARY KEY (TRA_OBS_ID));

COMMENT ON COLUMN TRANSFERENCIA_OBSERVACION.TRA_OBS_ID 		IS 'Identificador de la tabla.';
COMMENT ON COLUMN TRANSFERENCIA_OBSERVACION.FEC_CREACION	IS 'Fecha de creación del registro.';
COMMENT ON COLUMN TRANSFERENCIA_OBSERVACION.USU_ID		IS 'Identificador del usuario quien crea la observación.';
COMMENT ON COLUMN TRANSFERENCIA_OBSERVACION.TAR_ID		IS 'Identificador de la transferencia de archivo.';
COMMENT ON COLUMN TRANSFERENCIA_OBSERVACION.TRA_OBSERVACION	IS 'Descripción de la observación';

ALTER TABLE TRANSFERENCIA_OBSERVACION ADD CONSTRAINT FK_OBS_TRANSFERENCIA FOREIGN KEY (TAR_ID) REFERENCES TRANSFERENCIA_ARCHIVO (TAR_ID);
ALTER TABLE TRANSFERENCIA_OBSERVACION ADD CONSTRAINT FK_OBS_USUARIO FOREIGN KEY (USU_ID) REFERENCES USUARIO (USU_ID);

-- -----------------------------------------------------------------------------
-- TRANSFERENCIA_EXPEDIENTE_DETALLE
-- -----------------------------------------------------------------------------

CREATE SEQUENCE seq_TRANSFERENCIA_EXPEDIENTE_DETALLE;
CREATE TABLE TRANSFERENCIA_EXPEDIENTE_DETALLE (
  TRA_EXP_ID        number(10) NOT NULL, 
  TAR_ID            number(38) NOT NULL, 
  EXP_ID            number(10) NOT NULL, 
  ANTERIOR_QUIEN    number(38) NOT NULL, 
  ANTERIOR_DEP_ID   number(38) NOT NULL, 
  NUEVO_DEP_ID      number(38) NOT NULL, 
  NUEVO_QUIEN       number(38) NOT NULL, 
  FEC_TRANSFERENCIA date, 
  PRIMARY KEY (TRA_EXP_ID));

COMMENT ON COLUMN TRANSFERENCIA_EXPEDIENTE_DETALLE.TRA_EXP_ID 		IS 'Identificador de la tabla.';
COMMENT ON COLUMN TRANSFERENCIA_EXPEDIENTE_DETALLE.TAR_ID               IS 'Identificador de la transferencia de archivo.';
COMMENT ON COLUMN TRANSFERENCIA_EXPEDIENTE_DETALLE.EXP_ID		IS 'Identificador del expediente.';
COMMENT ON COLUMN TRANSFERENCIA_EXPEDIENTE_DETALLE.ANTERIOR_QUIEN	IS 'Identificador del usuario administrador anterior del expediente';
COMMENT ON COLUMN TRANSFERENCIA_EXPEDIENTE_DETALLE.ANTERIOR_DEP_ID	IS 'Identificador de la dependencia del usuario administrador anterior del expediente';
COMMENT ON COLUMN TRANSFERENCIA_EXPEDIENTE_DETALLE.NUEVO_DEP_ID		IS 'Identificador de la dependencia del usuario administrador nuevo del expediente';
COMMENT ON COLUMN TRANSFERENCIA_EXPEDIENTE_DETALLE.NUEVO_QUIEN          IS 'Identificador del usuario administrador nuevo del expediente';
COMMENT ON COLUMN TRANSFERENCIA_EXPEDIENTE_DETALLE.FEC_TRANSFERENCIA	IS 'Fecha de creación del registro.';

ALTER TABLE TRANSFERENCIA_EXPEDIENTE_DETALLE ADD CONSTRAINT FK_TED_DEP_ANTERIOR FOREIGN KEY (ANTERIOR_DEP_ID) REFERENCES DEPENDENCIA (DEP_ID);
ALTER TABLE TRANSFERENCIA_EXPEDIENTE_DETALLE ADD CONSTRAINT FK_TED_DEP_NUEVO FOREIGN KEY (NUEVO_DEP_ID) REFERENCES DEPENDENCIA (DEP_ID);
ALTER TABLE TRANSFERENCIA_EXPEDIENTE_DETALLE ADD CONSTRAINT FK_TED_EXPEDIENTE FOREIGN KEY (EXP_ID) REFERENCES EXPEDIENTE (EXP_ID);
ALTER TABLE TRANSFERENCIA_EXPEDIENTE_DETALLE ADD CONSTRAINT FK_TED_TAR FOREIGN KEY (TAR_ID) REFERENCES TRANSFERENCIA_ARCHIVO (TAR_ID);
ALTER TABLE TRANSFERENCIA_EXPEDIENTE_DETALLE ADD CONSTRAINT FK_TED_USU_ANTERIOR FOREIGN KEY (ANTERIOR_QUIEN) REFERENCES USUARIO (USU_ID);
ALTER TABLE TRANSFERENCIA_EXPEDIENTE_DETALLE ADD CONSTRAINT FK_TED_USU_NUEVO FOREIGN KEY (NUEVO_QUIEN) REFERENCES USUARIO (USU_ID);