/**
 * Author:  jgarcia
 * Created: 10/04/2018
 */

-- -----------------------------------------------------------------------------
-- TABLA: DEPENDENCIA_COPIA_MULTIDESTINO
-- -----------------------------------------------------------------------------

CREATE TABLE DEPENDENCIA_COPIA_MULTIDESTINO (
    DCM_ID                          NUMBER(38)          NOT NULL,
    DOC_ID_ORIGINAL                 VARCHAR2(32 CHAR)   NOT NULL,
    DEP_ID_DESTINO                  NUMBER(38)          NOT NULL,
    QUIEN                           NUMBER(38)          NOT NULL,
    CUANDO                          TIMESTAMP           NOT NULL,
    ACTIVO                          NUMBER(1)           NOT NULL,
    QUIEN_MOD                       NUMBER(38)          NULL,
    CUANDO_MOD                      TIMESTAMP           NULL,
    DOC_ID_RESULTADO                VARCHAR2(32 CHAR)   NULL,
    FECHAHORA_CREA_DOC_RESULTADO    TIMESTAMP           NULL,
    PRIMARY KEY (DCM_ID)
);

COMMENT ON TABLE DEPENDENCIA_COPIA_MULTIDESTINO 
IS 'Registros de documentos a dependencia copia por multidestino.';

COMMENT ON COLUMN DEPENDENCIA_COPIA_MULTIDESTINO.DCM_ID 
IS 'ID autonumérico.';
COMMENT ON COLUMN DEPENDENCIA_COPIA_MULTIDESTINO.DOC_ID_ORIGINAL 
IS 'ID del documento original.';
COMMENT ON COLUMN DEPENDENCIA_COPIA_MULTIDESTINO.DEP_ID_DESTINO 
IS 'ID de la dependencia destino de la copia.';
COMMENT ON COLUMN DEPENDENCIA_COPIA_MULTIDESTINO.QUIEN 
IS 'ID del usuario creador del registro.';
COMMENT ON COLUMN DEPENDENCIA_COPIA_MULTIDESTINO.CUANDO 
IS 'Fecha y hora de creación del registro.';
COMMENT ON COLUMN DEPENDENCIA_COPIA_MULTIDESTINO.ACTIVO 
IS 'Indicador de actividad (0=activo;1=inactivo).';
COMMENT ON COLUMN DEPENDENCIA_COPIA_MULTIDESTINO.QUIEN_MOD 
IS 'ID del usuario que eliminó el registro.';
COMMENT ON COLUMN DEPENDENCIA_COPIA_MULTIDESTINO.CUANDO_MOD 
IS 'Fecha y hora de eliminación del registro.';
COMMENT ON COLUMN DEPENDENCIA_COPIA_MULTIDESTINO.DOC_ID_RESULTADO 
IS 'ID del documento copia resultado para el registro.';
COMMENT ON COLUMN DEPENDENCIA_COPIA_MULTIDESTINO.FECHAHORA_CREA_DOC_RESULTADO 
IS 'Fecha y hora de creación del documento resultado.';

CREATE SEQUENCE DEPENDENCIA_COPIA_MULTIDES_SEQ;

ALTER TABLE DEPENDENCIA_COPIA_MULTIDESTINO
ADD CONSTRAINT DEP_COP_MULDES_DOC_ID_ORIG_FK
FOREIGN KEY (DOC_ID_ORIGINAL)
REFERENCES DOCUMENTO (DOC_ID);

ALTER TABLE DEPENDENCIA_COPIA_MULTIDESTINO
ADD CONSTRAINT DEP_COP_MULDES_DEP_ID_DEST_FK
FOREIGN KEY (DEP_ID_DESTINO)
REFERENCES DEPENDENCIA (DEP_ID);

ALTER TABLE DEPENDENCIA_COPIA_MULTIDESTINO
ADD CONSTRAINT DEP_COP_MULDES_QUIEN_FK
FOREIGN KEY (QUIEN)
REFERENCES USUARIO (USU_ID);

ALTER TABLE DEPENDENCIA_COPIA_MULTIDESTINO
ADD CONSTRAINT DEP_COP_MULDES_QUIEN_MOD_FK
FOREIGN KEY (QUIEN_MOD)
REFERENCES USUARIO (USU_ID);

ALTER TABLE DEPENDENCIA_COPIA_MULTIDESTINO
ADD CONSTRAINT DEP_COP_MULDES_DOC_ID_RESU_FK
FOREIGN KEY (DOC_ID_RESULTADO)
REFERENCES DOCUMENTO (DOC_ID);

CREATE INDEX DEP_COP_MULTIDES_ACTIVO_IDX 
ON DEPENDENCIA_COPIA_MULTIDESTINO (ACTIVO);