ALTER TABLE DEPENDENCIA ADD direccion VARCHAR2(500);
ALTER TABLE LOG ADD detalle_accion VARCHAR2(500);
ALTER TABLE LOG ADD DOC_ID VARCHAR2(32);
INSERT INTO ROL (ROL_ID,QUIEN,CUANDO,ACTIVO,ROL_NOMBRE) values ('ADMIN_LOG', 121,sysdate,1,'Administrador log');

DROP TABLE USUARIO_HISTORIAL_FIRMA_IMG;

CREATE TABLE USUARIO_HISTORIAL_FIRMA_IMG(QUIEN_MOD NUMBER(38,0) NOT NULL, USU_ID NUMBER(38,0) NOT NULL, USU_IMAGEN_FIRMA VARCHAR2(32), USU_IMAGEN_FIRMA_EXT	VARCHAR2(100), CUANDO TIMESTAMP NOT NULL );
