ALTER TABLE PLANTILLA ADD PLA_DOCX_DOCUMENTO VARCHAR2(100);
ALTER TABLE PLANTILLA ADD DOC_DOCX_DOCUMENTO VARCHAR2(100);

ALTER TABLE DOCUMENTO ADD FECHA_ULTI_TRG_EJECUTADO TIMESTAMP;

--crear carpeta en OFS z/z/z/z/  y archivo zzzz1234567890abcdefghijklmnopqrstuvwxyz


alter table DOCUMENTO_PDF ADD PDF_TEXTO57 VARCHAR(4000);
alter table DOCUMENTO_PDF ADD PDF_TEXTO58 VARCHAR(4000);
alter table DOCUMENTO_PDF ADD PDF_TEXTO59 VARCHAR(4000);
alter table DOCUMENTO_PDF ADD PDF_TEXTO60 VARCHAR(4000);
alter table DOCUMENTO_PDF ADD PDF_TEXTO61 VARCHAR(4000);
alter table DOCUMENTO_PDF ADD PDF_TEXTO62 VARCHAR(4000);
alter table DOCUMENTO_PDF ADD PDF_TEXTO63 VARCHAR(4000);
alter table DOCUMENTO_PDF ADD PDF_TEXTO64 VARCHAR(4000);
alter table DOCUMENTO_PDF ADD PDF_TEXTO65 VARCHAR(4000);
alter table DOCUMENTO_PDF ADD PDF_TEXTO66 VARCHAR(4000);
alter table DOCUMENTO_PDF ADD PDF_TEXTO67 VARCHAR(4000);
alter table DOCUMENTO_PDF ADD PDF_TEXTO68 VARCHAR(4000);
alter table DOCUMENTO_PDF ADD PDF_TEXTO69 VARCHAR(4000);
alter table DOCUMENTO_PDF ADD PDF_TEXTO70 VARCHAR(4000);



update proceso_transicion set PTR_DEFINICION = '/documento/asignar?pin={instancia.id}&tid={transicion.id}&mode=usuario' where PTR_ID = 82;


  CREATE TABLE DOCUMENTO_DEP_DESTINO(
    DDEP_ID VARCHAR2(32) NOT NULL, 	
    DOC_ID VARCHAR2(32)  NOT NULL, 	 	
    DEP_ID NUMBER(38,0) NOT NULL, 	
    QUIEN_MOD NUMBER(38,0) NOT NULL, 	
    CUANDO_MOD TIMESTAMP  NOT NULL, 	
    ACTIVO	NUMBER(1),
    CONSTRAINT "DOCUMENTO_DEP_DESTINO_PK" PRIMARY KEY ("DDEP_ID")  
  );

  
delete FROM DOCUMENTO_PDF;
delete FROM DOCUMENTO_ADJUNTO;
delete FROM DOCUMENTO_DEP_DESTINO;
delete FROM DOCUMENTO_DEPENDENCIA;  
delete FROM DOCUMENTO_OBS;
delete FROM DOCUMENTO_PRESTAMO;
delete FROM DOCUMENTO_USU_APRUEBA;
delete FROM DOCUMENTO_USU_ELABORA;
delete FROM DOCUMENTO_USU_FIRMA;
delete FROM DOCUMENTO_USU_VISTOS_BUENOS;
delete FROM LOG;
delete FROM DOCUMENTO;




create or replace FUNCTION FN_CON_USU_DOC_DEP_ADICIONAL
(
  P_USU_LOGIN IN USUARIO.USU_LOGIN%TYPE,
  P_DOC_ID IN DOCUMENTO.DOC_ID%TYPE
)
RETURN NUMBER is
  v_cantidad  NUMBER;
  BEGIN
    
      SELECT (
        SELECT 
        COUNT(distinct u.usu_login)
        from usuario u
        INNER JOIN DEPENDENCIA d ON d.usu_id_jefe = u.usu_id
        INNER JOIN DOCUMENTO_DEP_DESTINO ddp on u.dep_id = ddp.dep_id
        WHERE DOC_ID = P_DOC_ID AND TRIM(u.usu_login) = TRIM('iozunas') 
        ) INTO v_cantidad FROM DUAL;

    RETURN v_cantidad;
    
  END FN_CON_USU_DOC_DEP_ADICIONAL;
  
  
  
  Insert into ROL (ROL_ID,QUIEN,CUANDO,QUIEN_MOD,CUANDO_MOD,ACTIVO,ROL_NOMBRE) values ('REGISTRO','43',to_date('21/09/15','DD/MM/RR'),'12',to_date('21/09/15','DD/MM/RR'),'1','Documento registro');
  
  Insert into PROCESO_TRANSICION (PTR_ID,PTT_ID,PTR_DEFINICION,PTR_NOMBRE,PES_ID_INICIAL,PES_ID_FINAL,CUANDO,QUIEN,CUANDO_MOD,QUIEN_MOD,ACTIVO) values ('90','1','/documento/asignar-cualquiera-mi-dependencia?pin={instancia.id}&tid={transicion.id}','Dar respuesta','49','82',to_date('04/10/15','DD/MM/RR'),'12',to_date('26/11/15','DD/MM/RR'),'43','1');
  Insert into PROCESO_TRANSICION (PTR_ID,PTT_ID,PTR_DEFINICION,PTR_NOMBRE,PES_ID_INICIAL,PES_ID_FINAL,CUANDO,QUIEN,CUANDO_MOD,QUIEN_MOD,ACTIVO) values ('91','1','/documento/asignar-cualquiera-mi-dependencia?pin={instancia.id}&tid={transicion.id}','Archivar','49','81',to_date('04/10/15','DD/MM/RR'),'12',to_date('26/11/15','DD/MM/RR'),'43','1');

  update proceso_estado set PES_REASIGNACION = 1 where PES_ID = 49;
  
  
  
  
CREATE OR REPLACE PROCEDURE XIMENA_PRO AS 
BEGIN
  
  FOR rec IN (SELECT DEP_ID FROM DEPENDENCIA )
     LOOP
        --DBMS_OUTPUT.PUT_LINE( rec.DEP_ID );
        insert into dependencia_trd (DT_ID,DEP_ID,TRD_ID,ACTIVO,QUIEN,CUANDO) values( DEPENDENCIA_TRD_SEQ.nextval, rec.DEP_ID, 47, 1, 261, sysdate );
        insert into dependencia_trd (DT_ID,DEP_ID,TRD_ID,ACTIVO,QUIEN,CUANDO) values( DEPENDENCIA_TRD_SEQ.nextval, rec.DEP_ID, 59, 1, 261, sysdate );
        insert into dependencia_trd (DT_ID,DEP_ID,TRD_ID,ACTIVO,QUIEN,CUANDO) values( DEPENDENCIA_TRD_SEQ.nextval, rec.DEP_ID, 86, 1, 261, sysdate );        
        insert into dependencia_trd (DT_ID,DEP_ID,TRD_ID,ACTIVO,QUIEN,CUANDO) values( DEPENDENCIA_TRD_SEQ.nextval, rec.DEP_ID, 86, 1, 261, sysdate );    
     END LOOP;    
    commit;
END XIMENA_PRO;

--set SERVEROUTPUT ON
--BEGIN
--  XIMENA_PRO();
--END;


CREATE TABLE DOCUMENTO_SCANNER_CODIGO(
    DOCCOD_ID VARCHAR2(32) NOT NULL, 	
    DOCCOD_CODIGO VARCHAR2(6)  NOT NULL, 	 	
    DOCCOD_FECHA TIMESTAMP NOT NULL, 	
    QUIEN_MOD NUMBER(38,0) NOT NULL, 	
    CUANDO_MOD TIMESTAMP  NOT NULL, 	
    ACTIVO	NUMBER(1),
    CONSTRAINT "DDOCCOD_ID_COD_PK" PRIMARY KEY ("DOCCOD_ID")  
  );
  
  CREATE SEQUENCE DOCUMENTO_SCANNER_CODIGO_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
  
  
  CREATE TABLE DOCUMENTO_SCANNER_CODIGO(
    DOCCOD_ID VARCHAR2(32) NOT NULL, 	
    DOCCOD_CODIGO VARCHAR2(6)  NOT NULL,        
    QUIEN_MOD NUMBER(38,0) NOT NULL, 	
    CUANDO_MOD TIMESTAMP  NOT NULL, 	
    ACTIVO	NUMBER(1),
    CONSTRAINT "DDOCCOD_ID_COD_PK" PRIMARY KEY ("DOCCOD_ID")
  );
  drop table DOCUMENTO_SCANNER_CODIGO;
CREATE SEQUENCE DOCUMENTO_SCANNER_CODIGO_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;


alter table DOCUMENTO ADD CODIGO_VALIDA_SCANNER VARCHAR(6);
alter table DOCUMENTO ADD ID_USUARIO_VALIDA_COD_SCANNER NUMBER(38,0);
alter table DOCUMENTO ADD FECHA_GEN_CODIGO_SCANNER TIMESTAMP;
alter table DOCUMENTO ADD ESTADO_CODIGO_VALIDA_SCANNER NUMBER;


select index_name,index_type,status,domidx_status,domidx_opstatus from user_indexes where index_type like '%DOMAIN%' and (domidx_status <> 'VALID' or domidx_opstatus <> 'VALID');







drop trigger TRG_CAMBIO_USU_VISTO_DOCUMENTO;

alter table DOCUMENTO_PDF ADD PDF_TEXTO67 VARCHAR(4000);
alter table DOCUMENTO_PDF ADD PDF_TEXTO68 VARCHAR(4000);
alter table DOCUMENTO_PDF ADD PDF_TEXTO69 VARCHAR(4000);
alter table DOCUMENTO_PDF ADD PDF_TEXTO70 VARCHAR(4000);
alter table DOCUMENTO_PDF ADD PDF_TEXTO71 VARCHAR(4000);
alter table DOCUMENTO_PDF ADD PDF_TEXTO72 VARCHAR(4000);
alter table DOCUMENTO_PDF ADD PDF_TEXTO73 VARCHAR(4000);
alter table DOCUMENTO_PDF ADD PDF_TEXTO74 VARCHAR(4000);
alter table DOCUMENTO_PDF ADD PDF_TEXTO75 VARCHAR(4000);
alter table DOCUMENTO_PDF ADD PDF_TEXTO76 VARCHAR(4000);
alter table DOCUMENTO_PDF ADD PDF_TEXTO77 VARCHAR(4000);
alter table DOCUMENTO_PDF ADD PDF_TEXTO78 VARCHAR(4000);
alter table DOCUMENTO_PDF ADD PDF_TEXTO79 VARCHAR(4000);
alter table DOCUMENTO_PDF ADD PDF_TEXTO80 VARCHAR(4000);
alter table DOCUMENTO_PDF ADD PDF_TEXTO81 VARCHAR(4000);

VB_SGRADO_2
Vb_Nom_2
Vb_Cargo_2

VB_SGRADO_3
Vb_Nom_3
Vb_Cargo_3

VB_SGRADO_4
Vb_Nom_4
Vb_Cargo_4

VB_SGRADO_5
Vb_Nom_5
Vb_Cargo_5

VB_SGRADO_6
Vb_Nom_6
Vb_Cargo_6