create or replace PROCEDURE "PROC_COPIA_DOC_MULTIDESTINO"
(
  P_DOC_ID_ORIGEN   IN DOCUMENTO.DOC_ID%TYPE,
  P_PIN_ID_NUEVO    IN DOCUMENTO.PIN_ID%TYPE,
  P_DOC_ID_NUEVO    IN DOCUMENTO.DOC_ID%TYPE,
  P_DEP_ID_DES      IN DOCUMENTO.DEP_ID_DES%TYPE,
  P_ARRAY_UUID      T_ARRAY_UUID
)
is
    V_PIN_ID_ANTERIOR   DOCUMENTO.PIN_ID%TYPE;
    V_CANTIDAD          NUMBER;
    V_PIV_ID_NUEVO      PROCESO_INSTANCIA_VAR.PIV_ID%TYPE;
    V_PIV_KEY_ATR       PROCESO_INSTANCIA_VAR.PIV_KEY%TYPE := 'doc.id';

    CURSOR C_PIVAR  IS
    SELECT PIV_ID, PIN_ID, PIV_KEY, COUNT(1) CANTIDAD FROM H_PROCESO_INSTANCIA_VAR WHERE PIN_ID = V_PIN_ID_ANTERIOR GROUP BY PIV_ID, PIN_ID, PIV_KEY ORDER BY PIV_ID ASC;
    
    CURSOR C_PIVAR_INSERT (PIV_ID_INSERT NUMBER) IS
    SELECT * FROM H_PROCESO_INSTANCIA_VAR WHERE PIV_ID = PIV_ID_INSERT ORDER BY HPIV_ID ASC;
BEGIN

    BEGIN
        SELECT PIN_ID INTO V_PIN_ID_ANTERIOR FROM DOCUMENTO WHERE DOC_ID = P_DOC_ID_ORIGEN;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR( -20001, 'No se encontro el documento origen' );
    END;

    IF P_PIN_ID_NUEVO IS NULL THEN
        RAISE_APPLICATION_ERROR( -20001, 'El identificador de la tabla PROCESO_INSTANCIA esta vacío.' );
    END IF;
    
    SELECT COUNT(1) INTO V_CANTIDAD FROM PROCESO_INSTANCIA WHERE PIN_ID = P_PIN_ID_NUEVO;
    
    IF V_CANTIDAD > 0 THEN
        RAISE_APPLICATION_ERROR( -20001, 'El identificador nuevo de la tabla PROCESO_INSTANCIA ya se encuentró en el sistema.' );
    END IF;
        
    INSERT INTO PROCESO_INSTANCIA (SELECT P_PIN_ID_NUEVO,PRO_ID,CUANDO,QUIEN,PES_ID,CUANDO_MOD,QUIEN_MOD,USU_ID_ASIGNADO FROM PROCESO_INSTANCIA WHERE PIN_ID = V_PIN_ID_ANTERIOR);
    
    UPDATE PROCESO_INSTANCIA SET PES_ID = (SELECT PES_ID FROM PROCESO_INSTANCIA WHERE PIN_ID = V_PIN_ID_ANTERIOR) WHERE PIN_ID = P_PIN_ID_NUEVO;
    
    DELETE FROM H_PROCESO_INSTANCIA WHERE PIN_ID = P_PIN_ID_NUEVO;
    
    INSERT INTO H_PROCESO_INSTANCIA (PIN_ID, PRO_ID, CUANDO, QUIEN, PES_ID, CUANDO_MOD, QUIEN_MOD, USU_ID_ASIGNADO)
    (SELECT P_PIN_ID_NUEVO, PRO_ID, CUANDO, QUIEN, PES_ID, CUANDO_MOD, QUIEN_MOD, USU_ID_ASIGNADO FROM H_PROCESO_INSTANCIA a WHERE a.PIN_ID= V_PIN_ID_ANTERIOR);
    
    DELETE FROM PROCESO_INSTANCIA_VAR WHERE PIN_ID = P_PIN_ID_NUEVO;
    DELETE FROM H_PROCESO_INSTANCIA_VAR WHERE PIN_ID = P_PIN_ID_NUEVO;
    
    FOR AUX_C_PIVAR IN C_PIVAR LOOP
        V_CANTIDAD := 1;
        FOR AUX_C_PIVAR_INSERT IN C_PIVAR_INSERT(AUX_C_PIVAR.PIV_ID) LOOP
            IF V_CANTIDAD = 1 THEN
                INSERT INTO PROCESO_INSTANCIA_VAR (PIN_ID, PIV_KEY, PIV_VALUE, CUANDO, QUIEN, ACTIVO, CUANDO_MOD, QUIEN_MOD) VALUES
                (P_PIN_ID_NUEVO, AUX_C_PIVAR_INSERT.PIV_KEY, DECODE(AUX_C_PIVAR_INSERT.PIV_KEY, V_PIV_KEY_ATR,P_PIN_ID_NUEVO,AUX_C_PIVAR_INSERT.PIV_VALUE), AUX_C_PIVAR_INSERT.CUANDO, AUX_C_PIVAR_INSERT.QUIEN, AUX_C_PIVAR_INSERT.ACTIVO, AUX_C_PIVAR_INSERT.CUANDO_MOD, AUX_C_PIVAR_INSERT.QUIEN_MOD) RETURNING PIV_ID INTO V_PIV_ID_NUEVO ;
            ELSE
                UPDATE PROCESO_INSTANCIA_VAR
                SET PIV_VALUE   = DECODE(AUX_C_PIVAR_INSERT.PIV_KEY, V_PIV_KEY_ATR,P_PIN_ID_NUEVO,AUX_C_PIVAR_INSERT.PIV_VALUE),
                    CUANDO      = AUX_C_PIVAR_INSERT.CUANDO,
                    QUIEN       = AUX_C_PIVAR_INSERT.QUIEN,
                    ACTIVO      = AUX_C_PIVAR_INSERT.ACTIVO,
                    CUANDO_MOD  = AUX_C_PIVAR_INSERT.CUANDO_MOD,
                    QUIEN_MOD   = AUX_C_PIVAR_INSERT.QUIEN_MOD
                WHERE PIV_ID = V_PIV_ID_NUEVO;
            END IF;
            V_CANTIDAD := V_CANTIDAD + 1;
        END LOOP;
    END LOOP;
    
    INSERT INTO DOCUMENTO (DOC_ID, DOC_ASUNTO, TRD_ID, QUIEN, CUANDO, QUIEN_MOD, CUANDO_MOD, CLA_ID, DOC_NUM_OFICIO, DOC_PLAZO, DOC_FCH_OFICIO, DOC_NUM_FOLIOS, PIN_ID, DOC_STICKER, DOC_CONTENIDO, USU_ID_FIRMA, USU_ID_ELABORA, USU_ID_VISTO_BUENO, USU_ID_APRUEBA, DOC_RADICADO, DOC_RELACIONADO, EXP_ID, DOC_PDF, DOC_DESCRIPCION, DOC_PAGINAS, DEP_ID_DES, DOC_DEST_NOMBRE, DOC_DEST_TITULO, DOC_DEST_DIRECCION, PLA_ID, DOC_CONTENT_FILE, DOC_PRESTADO, DOC_REM_NOMBRE, DOC_REM_TITULO, DOC_REM_DIRECCION, DEP_ID_REM, PRO_RAD_ORFEO, PRO_NUM_BOLSA, ESTADO_TMP, PDF_TEXTO26, FECHA_ULTI_TRG_EJECUTADO, DOC_DOCX_DOCUMENTO, USU_ID_ULTIMA_ACCION, CODIGO_VALIDA_SCANNER, ID_USUARIO_VALIDA_COD_SCANNER, FECHA_GEN_CODIGO_SCANNER, ESTADO_CODIGO_VALIDA_SCANNER, GRADO_EXTERNO, MARCA_AGUA_EXTERNO, RESTRICCION_DIFUSION, CARGO_ID_ELABORA, CARGO_ID_FIRMA)
    (SELECT P_DOC_ID_NUEVO, DOC_ASUNTO, TRD_ID, QUIEN, CUANDO,QUIEN_MOD,CUANDO_MOD, CLA_ID,DOC_NUM_OFICIO, DOC_PLAZO, DOC_FCH_OFICIO, DOC_NUM_FOLIOS, P_PIN_ID_NUEVO, DOC_STICKER, DOC_CONTENIDO, USU_ID_FIRMA, USU_ID_ELABORA, USU_ID_VISTO_BUENO, USU_ID_APRUEBA, DOC_RADICADO, DOC_RELACIONADO, EXP_ID, DOC_PDF, DOC_DESCRIPCION, DOC_PAGINAS, P_DEP_ID_DES, DOC_DEST_NOMBRE, DOC_DEST_TITULO, DOC_DEST_DIRECCION, PLA_ID, DOC_CONTENT_FILE, DOC_PRESTADO, DOC_REM_NOMBRE, DOC_REM_TITULO, DOC_REM_DIRECCION, DEP_ID_REM, PRO_RAD_ORFEO, PRO_NUM_BOLSA, ESTADO_TMP, PDF_TEXTO26, FECHA_ULTI_TRG_EJECUTADO, DOC_DOCX_DOCUMENTO, USU_ID_ULTIMA_ACCION, CODIGO_VALIDA_SCANNER, ID_USUARIO_VALIDA_COD_SCANNER, FECHA_GEN_CODIGO_SCANNER, ESTADO_CODIGO_VALIDA_SCANNER, GRADO_EXTERNO, MARCA_AGUA_EXTERNO, RESTRICCION_DIFUSION, CARGO_ID_ELABORA, CARGO_ID_FIRMA FROM DOCUMENTO WHERE DOC_ID = P_DOC_ID_ORIGEN);
    
END "PROC_COPIA_DOC_MULTIDESTINO";