-- ------------------------------------------------------------ 
-- 2018-02-01 edison.gonzalez@controltechcg.com Issue #147 (SICDI-Controltech)
-- issue-147: Se realiza el ajuste para que tenga en cuenta la nueva columna 
-- DEP_IND_ENVIO_DOCUMENTOS de la tabla dependencia.
-- ------------------------------------------------------------
create or replace PROCEDURE       "PROC_PDF_ARBOL_DEPENDE" 
(
  P_DOC_ID IN DOCUMENTO.DOC_ID%TYPE,   
  P_DEP_ID IN DEPENDENCIA.DEP_ID%TYPE
) IS
  V_DEP_PADRE DEPENDENCIA.DEP_PADRE%TYPE;
  V_DEP_SIGLA DEPENDENCIA.DEP_SIGLA%TYPE;
  V_DEP_IND_ENVIO_DOCUMENTOS DEPENDENCIA.DEP_IND_ENVIO_DOCUMENTOS%TYPE;
BEGIN

  IF P_DEP_ID IS NOT NULL THEN

    SELECT DEP_PADRE, DEP_SIGLA, DEP_IND_ENVIO_DOCUMENTOS INTO V_DEP_PADRE,V_DEP_SIGLA,V_DEP_IND_ENVIO_DOCUMENTOS FROM DEPENDENCIA WHERE DEP_ID = P_DEP_ID;

    IF V_DEP_SIGLA IS NOT NULL THEN   
      INSERT INTO TMP_ARBOL_DEPEN VALUES (P_DOC_ID,CURRENT_TIMESTAMP,V_DEP_SIGLA);
    END IF;  

    IF V_DEP_PADRE IS NOT NULL AND NVL(V_DEP_IND_ENVIO_DOCUMENTOS,0) = 0 THEN      
      PROC_PDF_ARBOL_DEPENDE( P_DOC_ID, V_DEP_PADRE );
    END IF;    
  END IF;

END PROC_PDF_ARBOL_DEPENDE;