SET SERVEROUTPUT ON
DECLARE
    P_DOC_ID_ORIGEN VARCHAR2(4000) := '9df937851ac648588425b2d6543b9032';
    P_PIN_ID_NUEVO  VARCHAR2(4000) := '9';
    P_DOC_ID_NUEVO  VARCHAR2(4000) := '999';
    P_DEP_ID_DES    NUMBER         := 699;
    P_ARRAY_UUID    T_ARRAY_UUID   := T_ARRAY_UUID('abc','def','geh');
BEGIN
    PROC_COPIA_DOC_MULTIDESTINO(P_DOC_ID_ORIGEN,P_PIN_ID_NUEVO,P_DOC_ID_NUEVO,P_DEP_ID_DES,P_ARRAY_UUID);
END;
/

SELECT * FROM PROCESO_INSTANCIA WHERE PIN_ID = '9';
SELECT * FROM PROCESO_INSTANCIA WHERE PIN_ID = '9b9f005866c34d5eb75480a8ff3a9341';

SELECT * FROM PROCESO_INSTANCIA_VAR WHERE PIN_ID = '9';
SELECT * FROM PROCESO_INSTANCIA_VAR WHERE PIN_ID = '9b9f005866c34d5eb75480a8ff3a9341';

SELECT * FROM H_PROCESO_INSTANCIA WHERE PIN_ID = '9';
SELECT * FROM H_PROCESO_INSTANCIA WHERE PIN_ID = '9b9f005866c34d5eb75480a8ff3a9341';

SELECT * FROM H_PROCESO_INSTANCIA_VAR WHERE PIN_ID = '9';
SELECT * FROM H_PROCESO_INSTANCIA_VAR WHERE PIN_ID = '9b9f005866c34d5eb75480a8ff3a9341' ORDER BY HPIV_ID, PIV_ID;

SELECT * FROM INSTANCIA_BANDEJA WHERE PIN_ID = '9';
SELECT * FROM INSTANCIA_BANDEJA WHERE PIN_ID = '9b9f005866c34d5eb75480a8ff3a9341';

SELECT * FROM S_INSTANCIA_USUARIO WHERE PIN_ID = '9';
SELECT * FROM S_INSTANCIA_USUARIO WHERE PIN_ID = '9b9f005866c34d5eb75480a8ff3a9341';

SELECT * FROM DOCUMENTO WHERE PIN_ID = '9b9f005866c34d5eb75480a8ff3a9341';
SELECT * FROM DOCUMENTO WHERE PIN_ID = '9';

SELECT * FROM DOCUMENTO_ADJUNTO WHERE DOC_ID = '9';

SELECT * FROM DOCUMENTO_OBS WHERE DOC_ID = '9';
SELECT * FROM DOCUMENTO_PDF WHERE DOCPDF_ID = '9';
SELECT * FROM DOCUMENTO_USU_APRUEBA WHERE DOC_ID = '9';
SELECT * FROM DOCUMENTO_USU_ELABORA WHERE DOC_ID = '9';
SELECT * FROM DOCUMENTO_USU_FIRMA WHERE DOC_ID = '9';
SELECT * FROM DOCUMENTO_USU_VISTOS_BUENOS WHERE DOC_ID = '9';
SELECT * FROM DOCUMENTO_DEPENDENCIA WHERE DOC_ID = '9';
SELECT * FROM TMP_ARBOL_DEPEN WHERE DOC_ID = '9';



DELETE FROM PROCESO_INSTANCIA WHERE PIN_ID = '9';
DELETE FROM PROCESO_INSTANCIA_VAR WHERE PIN_ID = '9';
DELETE FROM H_PROCESO_INSTANCIA WHERE PIN_ID = '9';
DELETE FROM H_PROCESO_INSTANCIA_VAR WHERE PIN_ID = '9';
DELETE FROM INSTANCIA_BANDEJA WHERE PIN_ID = '9';
DELETE FROM S_INSTANCIA_USUARIO WHERE PIN_ID = '9';
DELETE FROM DOCUMENTO WHERE PIN_ID = '9';

DELETE FROM DOCUMENTO_ADJUNTO WHERE DOC_ID = '9';

DELETE FROM DOCUMENTO_OBS WHERE DOC_ID = '9';
DELETE FROM DOCUMENTO_PDF WHERE DOCPDF_ID = '9';
DELETE FROM DOCUMENTO_USU_APRUEBA WHERE DOC_ID = '9';
DELETE FROM DOCUMENTO_USU_ELABORA WHERE DOC_ID = '9';
DELETE FROM DOCUMENTO_USU_FIRMA WHERE DOC_ID = '9';
DELETE FROM DOCUMENTO_USU_VISTOS_BUENOS WHERE DOC_ID = '9';
DELETE FROM DOCUMENTO_DEPENDENCIA WHERE DOC_ID = '9';
DELETE FROM TMP_ARBOL_DEPEN WHERE DOC_ID = '9';
