-- 
-- 2018-03-06 edison.gonzalez@controltechcg.com Issue #151 (SICDI-Controltechcg).
-- Ajuste del trigger para guardar el cargo con el que se elaboro el documento.
create or replace TRIGGER TRG_CAMBIO_ELABORA_DOCUMENTO
AFTER INSERT OR UPDATE OF USU_ID_ELABORA,CARGO_ID_ELABORA on DOCUMENTO 
FOR EACH ROW WHEN (NEW.USU_ID_ELABORA IS NOT NULL OR NEW.CARGO_ID_ELABORA IS NOT NULL)
BEGIN
  IF (NVL(:OLD.USU_ID_ELABORA,0) != NVL(:NEW.USU_ID_ELABORA,0) OR NVL(:OLD.CARGO_ID_ELABORA,0) != NVL(:NEW.CARGO_ID_ELABORA,0)) THEN
    INSERT INTO DOCUMENTO_USU_ELABORA (DOC_ID, USU_ID_ELABORA, CUANDO, CARGO_ID_ELABORA) VALUES ( :NEW.DOC_ID, :NEW.USU_ID_ELABORA, SYSDATE, :NEW.CARGO_ID_ELABORA);
  END IF;    
END;
/