-- 
-- 2018-03-06 edison.gonzalez@controltechcg.com Issue #151 (SICDI-Controltechcg).
-- Ajuste del trigger para guardar el cargo con el que se firma el documento.
create or replace TRIGGER "DOC"."TRG_CAMBIO_USU_FIRMA_DOCUMENTO" 
AFTER INSERT OR UPDATE of USU_ID_FIRMA, CARGO_ID_FIRMA on DOCUMENTO 
FOR EACH ROW WHEN (NEW.USU_ID_FIRMA IS NOT NULL or NEW.CARGO_ID_FIRMA IS NOT NULL) 
BEGIN
    IF (NVL(:OLD.USU_ID_FIRMA,0) != NVL(:NEW.USU_ID_FIRMA,0) OR NVL(:OLD.CARGO_ID_FIRMA,0) != NVL(:NEW.CARGO_ID_FIRMA,0)) THEN
        INSERT INTO DOCUMENTO_USU_FIRMA (DOC_ID, USU_ID_FIRMA, CUANDO, CARGO_ID_FIRMA) VALUES ( :NEW.DOC_ID, :NEW.USU_ID_FIRMA, SYSDATE, :NEW.CARGO_ID_FIRMA);
    END IF;
END
;