-- 2017-04-18 jgarcia@controltechcg.com Issue #50 (SICDI-Controltech): 
-- Desactivar transición "Archivar" cuando se ha enviado el documento.

UPDATE PROCESO_TRANSICION SET ACTIVO = 0 WHERE PTR_ID = 91;

-- 2017-04-18 jgarcia@controltechcg.com Issue #50 (SICDI-Controltech):
-- Tabla de asignación para la bandeja de consulta.

CREATE TABLE DOCUMENTO_EN_CONSULTA
(
	DEC_ID		NUMBER(*,0) 					NOT NULL,
	DOC_ID		VARCHAR2(32 CHAR)				NOT NULL,
	ACTIVO		NUMBER(1,0)			DEFAULT 1	NOT NULL,
	QUIEN 		NUMBER(*,0) 		DEFAULT 0 	NOT NULL, 
	CUANDO 		DATE 							NOT NULL, 
	QUIEN_MOD	NUMBER(*,0), 
	CUANDO_MOD 	DATE, 
	PRIMARY KEY	(DEC_ID)
);

CREATE INDEX DOC_EN_CONSULTA_DOC_ID_IDX		ON DOCUMENTO_EN_CONSULTA (DOC_ID);
CREATE INDEX DOC_EN_CONSULTA_ACTIVO_IDX 	ON DOCUMENTO_EN_CONSULTA (ACTIVO);
CREATE INDEX DOC_EN_CONSULTA_QUIEN_IDX 		ON DOCUMENTO_EN_CONSULTA (QUIEN);
CREATE INDEX DOC_EN_CONSULTA_QUIEN_MOD_IDX	ON DOCUMENTO_EN_CONSULTA (QUIEN_MOD);

CREATE SEQUENCE DOCUMENTO_EN_CONSULTA_SEQ;