-- -----------------------------------------------------------------------------
-- 2018-02-07 edison.gonzalez@controltechcg.com Feature #149 (SICDI-Controntech)
-- feature-147
-- Estabilización de multiples cargos.
-- -----------------------------------------------------------------------------

-- -----------------------------------------------------------------------------
-- TABLA: CARGO
-- -----------------------------------------------------------------------------

drop table CARGO cascade constraints;
drop sequence CARGO_SEQ;
drop table CARGO_HISTORICO cascade constraints;
drop sequence CARGO_HISTORICO_SEQ;
drop table USUARIO_CARGO_HISTORICO cascade constraints;
drop sequence CARGO_HISTORICO_SEQ;

create table CARGO(
    "CAR_ID"        NUMBER(*,0)     NOT NULL,
    "CAR_NOMBRE"    VARCHAR2(200)   NOT NULL,
    "CAR_IND_LDAP"  NUMBER(1,0)     DEFAULT 0 NOT NULL,
    "QUIEN"         NUMBER(*,0)     NOT NULL,
    "CUANDO"        TIMESTAMP       NOT NULL,
    "QUIEN_MOD"     NUMBER(*,0),
    "CUANDO_MOD"    TIMESTAMP,
    CONSTRAINT "CARGO_PK" PRIMARY KEY ("CAR_ID"),
    CONSTRAINT CARGO_unique UNIQUE ("CAR_NOMBRE"),
    CONSTRAINT "CARGO_FK1" FOREIGN KEY ("QUIEN")
    REFERENCES "DOC"."USUARIO" ("USU_ID"),
    CONSTRAINT "CARGO_FK2" FOREIGN KEY ("QUIEN_MOD")
    REFERENCES "DOC"."USUARIO" ("USU_ID")
);

COMMENT ON COLUMN DOC.CARGO.CAR_ID IS 'Identificador único de la tabla';
COMMENT ON COLUMN DOC.CARGO.CAR_NOMBRE IS 'Descripción del cargo.';
COMMENT ON COLUMN DOC.CARGO.CAR_IND_LDAP IS 'Permite identificar si el cargo es creado por el LDAP. 0=No; 1=Si';
COMMENT ON COLUMN DOC.CARGO.QUIEN IS 'Identificador del usuario quién crea el registro; Si el cargo es creado por el LDAP se inserta el usuario quien creo el usuario en el sistema';
COMMENT ON COLUMN DOC.CARGO.CUANDO IS 'Fecha en la cual se creo el registro';
COMMENT ON COLUMN DOC.CARGO.QUIEN_MOD IS 'Identifica el usuario quien modifica el registro';
COMMENT ON COLUMN DOC.CARGO.CUANDO_MOD IS 'Fecha en la cual se modifica el registro';

CREATE INDEX CARGO_IDX1 ON CARGO(QUIEN);
CREATE INDEX CARGO_IDX2 ON CARGO(QUIEN_MOD);

CREATE SEQUENCE  "DOC"."CARGO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1;

-- -----------------------------------------------------------------------------
-- TABLA: CARGO_HISTORICO
-- -----------------------------------------------------------------------------

create table CARGO_HISTORICO(
    CAR_HIS_ID              NUMBER(*,0)     NOT NULL,
    "CAR_ID"                NUMBER(*,0)     NOT NULL,
    CAR_NOMBRE_ANTERIOR     VARCHAR2(200)   NOT NULL,
    CAR_HIS_FEC_MOD         TIMESTAMP       NOT NULL,
    CAR_HIS_USU_MOD         NUMBER(*,0)     NOT NULL, 
    CONSTRAINT "CARGO_HISTORICO_PK" PRIMARY KEY ("CAR_HIS_ID"),
    CONSTRAINT "CARGO_HISTORICO_FK1" FOREIGN KEY ("CAR_ID") REFERENCES "DOC"."CARGO" ("CAR_ID"),
    CONSTRAINT "CARGO_HISTORICO_FK2" FOREIGN KEY ("CAR_HIS_USU_MOD") REFERENCES "DOC"."USUARIO" ("USU_ID")
);

COMMENT ON COLUMN DOC.CARGO_HISTORICO.CAR_HIS_ID IS 'Identificador único de la tabla';
COMMENT ON COLUMN DOC.CARGO_HISTORICO.CAR_ID IS 'Identificador del cargo modificado.';
COMMENT ON COLUMN DOC.CARGO_HISTORICO.CAR_NOMBRE_ANTERIOR IS 'Descripción del cargo como se encontraba antes de su modificación';
COMMENT ON COLUMN DOC.CARGO_HISTORICO.CAR_HIS_USU_MOD IS 'Identificador del usuario quién modificó la descripción del cargo';
COMMENT ON COLUMN DOC.CARGO_HISTORICO.CAR_HIS_FEC_MOD IS 'Fecha en la cual se modifica la descripción del cargo';

CREATE SEQUENCE  "DOC"."CARGO_HISTORICO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1;

CREATE INDEX CARGO_HISTORICO_IDX1 ON CARGO_HISTORICO(CAR_ID);
CREATE INDEX CARGO_HISTORICO_IDX2 ON CARGO_HISTORICO(CAR_HIS_USU_MOD);
CREATE INDEX CARGO_HISTORICO_IDX3 ON CARGO_HISTORICO(CAR_HIS_FEC_MOD);

-- -----------------------------------------------------------------------------
-- TABLA: USUARIO
-- -----------------------------------------------------------------------------

ALTER TABLE USUARIO ADD USU_CARGO_PRINCIPAL_ID NUMBER(*,0);
ALTER TABLE USUARIO ADD USU_CARGO1_ID NUMBER(*,0);
ALTER TABLE USUARIO ADD USU_CARGO2_ID NUMBER(*,0);
ALTER TABLE USUARIO ADD USU_CARGO3_ID NUMBER(*,0);
ALTER TABLE USUARIO ADD USU_CARGO4_ID NUMBER(*,0);
ALTER TABLE USUARIO ADD USU_CARGO5_ID NUMBER(*,0);
ALTER TABLE USUARIO ADD USU_CARGO6_ID NUMBER(*,0);
ALTER TABLE USUARIO ADD USU_CARGO7_ID NUMBER(*,0);
ALTER TABLE USUARIO ADD USU_CARGO8_ID NUMBER(*,0);
ALTER TABLE USUARIO ADD USU_CARGO9_ID NUMBER(*,0);
ALTER TABLE USUARIO ADD USU_CARGO10_ID NUMBER(*,0);

COMMENT ON COLUMN DOC.USUARIO.USU_CARGO_PRINCIPAL_ID IS 'Identificador del cargo que se encuentra relacionado en el LDAP';
COMMENT ON COLUMN DOC.USUARIO.USU_CARGO1_ID IS 'Identificador del cargo alternativo #1';
COMMENT ON COLUMN DOC.USUARIO.USU_CARGO2_ID IS 'Identificador del cargo alternativo #2';
COMMENT ON COLUMN DOC.USUARIO.USU_CARGO3_ID IS 'Identificador del cargo alternativo #3';
COMMENT ON COLUMN DOC.USUARIO.USU_CARGO4_ID IS 'Identificador del cargo alternativo #4';
COMMENT ON COLUMN DOC.USUARIO.USU_CARGO5_ID IS 'Identificador del cargo alternativo #5';
COMMENT ON COLUMN DOC.USUARIO.USU_CARGO6_ID IS 'Identificador del cargo alternativo #6';
COMMENT ON COLUMN DOC.USUARIO.USU_CARGO7_ID IS 'Identificador del cargo alternativo #7';
COMMENT ON COLUMN DOC.USUARIO.USU_CARGO8_ID IS 'Identificador del cargo alternativo #8';
COMMENT ON COLUMN DOC.USUARIO.USU_CARGO9_ID IS 'Identificador del cargo alternativo #9';
COMMENT ON COLUMN DOC.USUARIO.USU_CARGO10_ID IS 'Identificador del cargo alternativo #10';

ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_FK1 FOREIGN KEY (USU_CARGO_PRINCIPAL_ID) REFERENCES CARGO (CAR_ID);
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_FK2 FOREIGN KEY (USU_CARGO1_ID) REFERENCES CARGO (CAR_ID);
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_FK3 FOREIGN KEY (USU_CARGO2_ID) REFERENCES CARGO (CAR_ID);
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_FK4 FOREIGN KEY (USU_CARGO3_ID) REFERENCES CARGO (CAR_ID);
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_FK5 FOREIGN KEY (USU_CARGO4_ID) REFERENCES CARGO (CAR_ID);
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_FK6 FOREIGN KEY (USU_CARGO5_ID) REFERENCES CARGO (CAR_ID);
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_FK7 FOREIGN KEY (USU_CARGO6_ID) REFERENCES CARGO (CAR_ID);
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_FK8 FOREIGN KEY (USU_CARGO7_ID) REFERENCES CARGO (CAR_ID);
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_FK9 FOREIGN KEY (USU_CARGO8_ID) REFERENCES CARGO (CAR_ID);
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_FK10 FOREIGN KEY (USU_CARGO9_ID) REFERENCES CARGO (CAR_ID);
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_FK11 FOREIGN KEY (USU_CARGO10_ID) REFERENCES CARGO (CAR_ID);

CREATE INDEX USUARIO_IDX1 ON USUARIO(USU_CARGO_PRINCIPAL_ID);
CREATE INDEX USUARIO_IDX2 ON USUARIO(USU_CARGO1_ID);
CREATE INDEX USUARIO_IDX3 ON USUARIO(USU_CARGO2_ID);
CREATE INDEX USUARIO_IDX4 ON USUARIO(USU_CARGO3_ID);
CREATE INDEX USUARIO_IDX5 ON USUARIO(USU_CARGO4_ID);
CREATE INDEX USUARIO_IDX6 ON USUARIO(USU_CARGO5_ID);
CREATE INDEX USUARIO_IDX7 ON USUARIO(USU_CARGO6_ID);
CREATE INDEX USUARIO_IDX8 ON USUARIO(USU_CARGO7_ID);
CREATE INDEX USUARIO_IDX9 ON USUARIO(USU_CARGO8_ID);
CREATE INDEX USUARIO_IDX10 ON USUARIO(USU_CARGO9_ID);
CREATE INDEX USUARIO_IDX11 ON USUARIO(USU_CARGO10_ID);

-- -----------------------------------------------------------------------------
-- TABLA: USUARIO_CARGO_HISTORICO
-- -----------------------------------------------------------------------------

create table USUARIO_CARGO_HISTORICO(
    "USU_CAR_HIS_ID"                NUMBER(*,0)     NOT NULL,
    "USU_ID"                        NUMBER(*,0)     NOT NULL,
    CARGO_PRINCIPAL_ANTERIOR        NUMBER(*,0),
    CARGO1_ID_ANTERIOR              NUMBER(*,0),
    CARGO2_ID_ANTERIOR              NUMBER(*,0),
    CARGO3_ID_ANTERIOR              NUMBER(*,0),
    CARGO4_ID_ANTERIOR              NUMBER(*,0),
    CARGO5_ID_ANTERIOR              NUMBER(*,0),
    CARGO6_ID_ANTERIOR              NUMBER(*,0),
    CARGO7_ID_ANTERIOR              NUMBER(*,0),
    CARGO8_ID_ANTERIOR              NUMBER(*,0),
    CARGO9_ID_ANTERIOR              NUMBER(*,0),
    CARGO10_ID_ANTERIOR             NUMBER(*,0),
    CAR_HIS_FEC_MOD                 TIMESTAMP       NOT NULL,
    USU_CAR_HIS_USU_MOD             NUMBER(*,0)     NOT NULL, 
    CONSTRAINT "USUARIO_CARGO_HISTORICO_PK" PRIMARY KEY ("USU_CAR_HIS_ID"),
    CONSTRAINT "USUARIO_CARGO_HISTORICO_FK1" FOREIGN KEY ("USU_ID") REFERENCES "DOC"."USUARIO" ("USU_ID"),
    CONSTRAINT "USUARIO_CARGO_HISTORICO_FK2" FOREIGN KEY ("CARGO1_ID_ANTERIOR") REFERENCES "DOC"."CARGO" ("CAR_ID"),
    CONSTRAINT "USUARIO_CARGO_HISTORICO_FK3" FOREIGN KEY ("CARGO2_ID_ANTERIOR") REFERENCES "DOC"."CARGO" ("CAR_ID"),
    CONSTRAINT "USUARIO_CARGO_HISTORICO_FK4" FOREIGN KEY ("CARGO3_ID_ANTERIOR") REFERENCES "DOC"."CARGO" ("CAR_ID"),
    CONSTRAINT "USUARIO_CARGO_HISTORICO_FK5" FOREIGN KEY ("CARGO4_ID_ANTERIOR") REFERENCES "DOC"."CARGO" ("CAR_ID"),
    CONSTRAINT "USUARIO_CARGO_HISTORICO_FK6" FOREIGN KEY ("CARGO5_ID_ANTERIOR") REFERENCES "DOC"."CARGO" ("CAR_ID"),
    CONSTRAINT "USUARIO_CARGO_HISTORICO_FK7" FOREIGN KEY ("CARGO6_ID_ANTERIOR") REFERENCES "DOC"."CARGO" ("CAR_ID"),
    CONSTRAINT "USUARIO_CARGO_HISTORICO_FK8" FOREIGN KEY ("CARGO7_ID_ANTERIOR") REFERENCES "DOC"."CARGO" ("CAR_ID"),
    CONSTRAINT "USUARIO_CARGO_HISTORICO_FK9" FOREIGN KEY ("CARGO8_ID_ANTERIOR") REFERENCES "DOC"."CARGO" ("CAR_ID"),
    CONSTRAINT "USUARIO_CARGO_HISTORICO_FK10" FOREIGN KEY ("CARGO9_ID_ANTERIOR") REFERENCES "DOC"."CARGO" ("CAR_ID"),
    CONSTRAINT "USUARIO_CARGO_HISTORICO_FK11" FOREIGN KEY ("CARGO10_ID_ANTERIOR") REFERENCES "DOC"."CARGO" ("CAR_ID"),
    CONSTRAINT "USUARIO_CARGO_HISTORICO_FK12" FOREIGN KEY ("CARGO_PRINCIPAL_ANTERIOR") REFERENCES "DOC"."CARGO" ("CAR_ID"),
    CONSTRAINT "USUARIO_CARGO_HISTORICO_FK13" FOREIGN KEY ("USU_CAR_HIS_USU_MOD") REFERENCES "DOC"."USUARIO" ("USU_ID")
);

COMMENT ON COLUMN DOC.USUARIO_CARGO_HISTORICO.CAR_HIS_ID IS 'Identificador único de la tabla';
COMMENT ON COLUMN DOC.USUARIO_CARGO_HISTORICO.USU_ID IS 'Identificador del usuario.';
COMMENT ON COLUMN DOC.USUARIO_CARGO_HISTORICO.CARGO_PRINCIPAL_ANTERIOR IS 'Descripción del cargo principal antes de su modificación';
COMMENT ON COLUMN DOC.USUARIO_CARGO_HISTORICO.CARGO1_ID_ANTERIOR IS 'Identificador del cargo alterno #1 antes de su modificación';
COMMENT ON COLUMN DOC.USUARIO_CARGO_HISTORICO.CARGO2_ID_ANTERIOR IS 'Identificador del cargo alterno #2 antes de su modificación';
COMMENT ON COLUMN DOC.USUARIO_CARGO_HISTORICO.CARGO3_ID_ANTERIOR IS 'Identificador del cargo alterno #3 antes de su modificación';
COMMENT ON COLUMN DOC.USUARIO_CARGO_HISTORICO.CARGO4_ID_ANTERIOR IS 'Identificador del cargo alterno #4 antes de su modificación';
COMMENT ON COLUMN DOC.USUARIO_CARGO_HISTORICO.CARGO5_ID_ANTERIOR IS 'Identificador del cargo alterno #5 antes de su modificación';
COMMENT ON COLUMN DOC.USUARIO_CARGO_HISTORICO.CARGO6_ID_ANTERIOR IS 'Identificador del cargo alterno #6 antes de su modificación';
COMMENT ON COLUMN DOC.USUARIO_CARGO_HISTORICO.CARGO7_ID_ANTERIOR IS 'Identificador del cargo alterno #7 antes de su modificación';
COMMENT ON COLUMN DOC.USUARIO_CARGO_HISTORICO.CARGO8_ID_ANTERIOR IS 'Identificador del cargo alterno #8 antes de su modificación';
COMMENT ON COLUMN DOC.USUARIO_CARGO_HISTORICO.CARGO9_ID_ANTERIOR IS 'Identificador del cargo alterno #9 antes de su modificación';
COMMENT ON COLUMN DOC.USUARIO_CARGO_HISTORICO.CARGO10_ID_ANTERIOR IS 'Identificador del cargo alterno #10 antes de su modificación';
COMMENT ON COLUMN DOC.USUARIO_CARGO_HISTORICO.CAR_HIS_FEC_MOD IS 'Fecha en la cual se modifica el/los cargo(s) del usuario';
COMMENT ON COLUMN DOC.USUARIO_CARGO_HISTORICO.USU_CAR_HIS_USU_MOD IS 'Identificador del usuario quién modifica el/los cargo(s) del usuario';

CREATE SEQUENCE  "DOC"."USUARIO_CARGO_HISTORICO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1;

CREATE INDEX USUARIO_CARGO_HISTORICO_IDX1 ON USUARIO_CARGO_HISTORICO(USU_ID);
CREATE INDEX USUARIO_CARGO_HISTORICO_IDX2 ON USUARIO_CARGO_HISTORICO(CARGO_PRINCIPAL_ANTERIOR);
CREATE INDEX USUARIO_CARGO_HISTORICO_IDX3 ON USUARIO_CARGO_HISTORICO(CARGO1_ID_ANTERIOR);
CREATE INDEX USUARIO_CARGO_HISTORICO_IDX4 ON USUARIO_CARGO_HISTORICO(CARGO2_ID_ANTERIOR);
CREATE INDEX USUARIO_CARGO_HISTORICO_IDX5 ON USUARIO_CARGO_HISTORICO(CARGO3_ID_ANTERIOR);
CREATE INDEX USUARIO_CARGO_HISTORICO_IDX6 ON USUARIO_CARGO_HISTORICO(CARGO4_ID_ANTERIOR);
CREATE INDEX USUARIO_CARGO_HISTORICO_IDX7 ON USUARIO_CARGO_HISTORICO(CARGO5_ID_ANTERIOR);
CREATE INDEX USUARIO_CARGO_HISTORICO_IDX8 ON USUARIO_CARGO_HISTORICO(CARGO6_ID_ANTERIOR);
CREATE INDEX USUARIO_CARGO_HISTORICO_IDX9 ON USUARIO_CARGO_HISTORICO(CARGO7_ID_ANTERIOR);
CREATE INDEX USUARIO_CARGO_HISTORICO_IDX10 ON USUARIO_CARGO_HISTORICO(CARGO8_ID_ANTERIOR);
CREATE INDEX USUARIO_CARGO_HISTORICO_IDX11 ON USUARIO_CARGO_HISTORICO(CARGO9_ID_ANTERIOR);
CREATE INDEX USUARIO_CARGO_HISTORICO_IDX12 ON USUARIO_CARGO_HISTORICO(CARGO10_ID_ANTERIOR);