--
-- Lista de instrucciones SQL para reversar las operaciones realizadas por el
-- procedimiento PL/SQL "PROC_COPIA_DOC_MULTIDESTINO".
-- Author: jgarcia@controltechcg.com
-- Date: 05/17/2018 Issue #165 (SICDI-Controltech) hotfix-165
--

DELETE FROM PROCESO_INSTANCIA       WHERE PIN_ID = :P_PIN_ID_NUEVO;
DELETE FROM H_PROCESO_INSTANCIA     WHERE PIN_ID = :P_PIN_ID_NUEVO;
DELETE FROM PROCESO_INSTANCIA_VAR   WHERE PIN_ID = :P_PIN_ID_NUEVO;
DELETE FROM H_PROCESO_INSTANCIA_VAR WHERE PIN_ID = :P_PIN_ID_NUEVO;
DELETE FROM S_INSTANCIA_USUARIO     WHERE PIN_ID = :P_PIN_ID_NUEVO;
DELETE FROM DOCUMENTO               WHERE PIN_ID = :P_PIN_ID_NUEVO;

DELETE FROM DOCUMENTO_ADJUNTO           WHERE DOC_ID    = :P_DOC_ID_NUEVO;
DELETE FROM DOCUMENTO_OBS               WHERE DOC_ID    = :P_DOC_ID_NUEVO;
DELETE FROM DOCUMENTO_PDF               WHERE DOCPDF_ID = :P_DOC_ID_NUEVO;
DELETE FROM DOCUMENTO_USU_ELABORA       WHERE DOC_ID    = :P_DOC_ID_NUEVO;
DELETE FROM DOCUMENTO_USU_APRUEBA       WHERE DOC_ID    = :P_DOC_ID_NUEVO;
DELETE FROM DOCUMENTO_USU_VISTOS_BUENOS WHERE DOC_ID    = :P_DOC_ID_NUEVO;